export const CALLS = [
  {
    id: 'S01',
    pods: ['J', 'K'],
    audio: '/audio/FO-S01.mp3',
    duration: 1.673,
    waveform: '/images/callcatalog/waveforms/S01.png',
    colorSpec: '/images/callcatalog/FO-S01.png',
    bwSpec: '/images/callcatalog/S01.png',
  },
  {
    id: 'S02',
    pods: ['J', 'L'],
    audio: '/audio/FO-S02.mp3',
    duration: 2.946,
    waveform: '/images/callcatalog/waveforms/S02.png',
    colorSpec: '/images/callcatalog/FO-S02.png',
    bwSpec: '/images/callcatalog/S02.png',
  },
  {
    id: 'S03',
    pods: ['J'],
    audio: '/audio/FO-S03.mp3',
    duration: 3.455,
    waveform: '/images/callcatalog/waveforms/S03.png',
    colorSpec: '/images/callcatalog/FO-S03.png',
    bwSpec: '/images/callcatalog/S03.png',
  },
  {
    id: 'S04',
    pods: ['J', 'K'],
    audio: '/audio/FO-S04.mp3',
    duration: 1.564,
    waveform: '/images/callcatalog/waveforms/S04.png',
    colorSpec: '/images/callcatalog/FO-S04.png',
    bwSpec: '/images/callcatalog/S04.png',
  },
  {
    id: 'S05',
    pods: ['J', 'K'],
    audio: '/audio/FO-S05.mp3',
    duration: 0.618,
    waveform: '/images/callcatalog/waveforms/S05.png',
    colorSpec: '/images/callcatalog/FO-S05.png',
    bwSpec: '/images/callcatalog/S05.png',
  },
  {
    id: 'S06a',
    pods: ['J', 'K', 'L'],
    audio: '/audio/FO-S06-a.mp3',
    duration: 0.873,
    waveform: '/images/callcatalog/waveforms/S06a.png',
    colorSpec: '/images/callcatalog/FO-S06-a.png',
    bwSpec: '/images/callcatalog/S06.png',
  },
  {
    id: 'S06b',
    pods: ['J', 'K', 'L'],
    audio: '/audio/FO-S06-b.mp3',
    duration: 0.873,
    waveform: '/images/callcatalog/waveforms/S06b.png',
    colorSpec: '/images/callcatalog/FO-S06-b.png',
    bwSpec: null,
  },
  {
    id: 'S06c',
    pods: ['J', 'K', 'L'],
    audio: '/audio/FO-S06-c.mp3',
    duration: 0.837,
    waveform: '/images/callcatalog/waveforms/S06c.png',
    colorSpec: '/images/callcatalog/FO-S06-c.png',
    bwSpec: null,
  },
  {
    id: 'S06-L',
    label: 'S06L',
    pods: ['J', 'K', 'L'],
    audio: '/audio/FO-S06-L.mp3',
    duration: 1.273,
    waveform: '/images/callcatalog/waveforms/S06-L.png',
    colorSpec: '/images/callcatalog/FO-S06-L.png',
    bwSpec: null,
  },
  {
    id: 'S07',
    pods: ['J', 'K'],
    audio: '/audio/FO-S07.mp3',
    duration: 1.491,
    waveform: '/images/callcatalog/waveforms/S07.png',
    colorSpec: '/images/callcatalog/FO-S07.png',
    bwSpec: '/images/callcatalog/S07.png',
  },
  {
    id: 'S08',
    pods: ['J', 'K', 'L'],
    audio: null,
    colorSpec: null,
    bwSpec: '/images/callcatalog/S08i+ii.png',
  },
  {
    id: 'S09',
    pods: ['J'],
    audio: '/audio/FO-S09.mp3',
    duration: 1.381,
    waveform: '/images/callcatalog/waveforms/S09.png',
    colorSpec: '/images/callcatalog/FO-S09.png',
    bwSpec: '/images/callcatalog/S09.png',
  },
  {
    id: 'S10',
    pods: ['J', 'K', 'L'],
    audio: '/audio/FO-S10.mp3',
    duration: 1.497,
    waveform: '/images/callcatalog/waveforms/S10.png',
    colorSpec: '/images/callcatalog/FO-S10.png',
    bwSpec: '/images/callcatalog/S10.png',
  },
  {
    id: 'S12',
    pods: ['J'],
    audio: null,
    colorSpec: null,
    bwSpec: '/images/callcatalog/S12.png',
  },
  {
    id: 'S13',
    pods: ['J', 'L'],
    audio: '/audio/FO-S13.mp3',
    duration: 0.873,
    waveform: '/images/callcatalog/waveforms/S13.png',
    colorSpec: '/images/callcatalog/FO-S13.png',
    bwSpec: '/images/callcatalog/S13.png',
  },
  {
    id: 'S14',
    pods: ['J'],
    audio: '/audio/FO-S14.mp3',
    duration: 0.969,
    waveform: '/images/callcatalog/waveforms/S14.png',
    colorSpec: '/images/callcatalog/FO-S14.png',
    bwSpec: '/images/callcatalog/S14.png',
  },
  {
    id: 'S16',
    pods: ['K', 'L'],
    audio: '/audio/FO-S16.mp3',
    duration: 1.235,
    waveform: '/images/callcatalog/waveforms/S16.png',
    colorSpec: '/images/callcatalog/FO-S16.png',
    bwSpec: '/images/callcatalog/S16.png',
  },
  {
    id: 'S17',
    pods: ['K', 'L'],
    audio: '/audio/FO-S17.mp3',
    duration: 1.641,
    waveform: '/images/callcatalog/waveforms/S17.png',
    colorSpec: '/images/callcatalog/FO-S17.png',
    bwSpec: '/images/callcatalog/S17.png',
  },
  {
    id: 'S18',
    pods: ['L'],
    audio: '/audio/FO-S18-R.mp3',
    duration: 1.391,
    waveform: '/images/callcatalog/waveforms/S18.png',
    colorSpec: '/images/callcatalog/FO-S18-R.png',
    bwSpec: '/images/callcatalog/S18.png',
  },
  {
    id: 'S19',
    pods: ['L'],
    audio: '/audio/FO-S19.mp3',
    duration: 1.141,
    waveform: '/images/callcatalog/waveforms/S19.png',
    colorSpec: '/images/callcatalog/FO-S19.png',
    bwSpec: '/images/callcatalog/S19.png',
  },
  {
    id: 'S22a',
    pods: ['L'],
    audio: '/audio/FO-S22-a.mp3',
    duration: 0.485,
    waveform: '/images/callcatalog/waveforms/S22a.png',
    colorSpec: '/images/callcatalog/FO-S22-a.png',
    bwSpec: '/images/callcatalog/S22.png',
  },
  {
    id: 'S22b',
    pods: ['L'],
    audio: '/audio/FO-S22-b.mp3',
    duration: 0.617,
    waveform: '/images/callcatalog/waveforms/S22b.png',
    colorSpec: '/images/callcatalog/FO-S22-b.png',
    bwSpec: '/images/callcatalog/S22.png',
  },
  {
    id: 'S30',
    pods: [],
    audio: '/audio/FO-S30.mp3',
    duration: 0.938,
    waveform: '/images/callcatalog/waveforms/S30.png',
    colorSpec: '/images/callcatalog/FO-S30.png',
    bwSpec: null,
  },
  {
    id: 'S31a',
    pods: ['L'],
    audio: '/audio/FO-S31-a.mp3',
    duration: 0.578,
    waveform: '/images/callcatalog/waveforms/S31a.png',
    colorSpec: '/images/callcatalog/FO-S31-a.png',
    bwSpec: '/images/callcatalog/S31.png',
  },
  {
    id: 'S31b',
    pods: ['L'],
    audio: '/audio/FO-S31-b.mp3',
    duration: 0.703,
    waveform: '/images/callcatalog/waveforms/S31b.png',
    colorSpec: '/images/callcatalog/FO-S31-b.png',
    bwSpec: '/images/callcatalog/S31.png',
  },
  {
    id: 'S31c',
    pods: ['L'],
    audio: '/audio/FO-S31-c.mp3',
    duration: 0.719,
    waveform: '/images/callcatalog/waveforms/S31c.png',
    colorSpec: '/images/callcatalog/FO-S31-c.png',
    bwSpec: '/images/callcatalog/S31.png',
  },
  {
    id: 'S33R',
    pods: ['L'],
    audio: '/audio/FO-S33-R.mp3',
    duration: 0.985,
    waveform: '/images/callcatalog/waveforms/S33R.png',
    colorSpec: '/images/callcatalog/FO-S33-R.png',
    bwSpec: '/images/callcatalog/S33.png',
  },
  {
    id: 'S33RJ-a',
    pods: ['L'],
    audio: '/audio/FO-S33-RJ-a.mp3',
    duration: 1.172,
    waveform: '/images/callcatalog/waveforms/S33RJ-a.png',
    colorSpec: '/images/callcatalog/FO-S33-RJ-a.png',
    bwSpec: '/images/callcatalog/S33.png',
  },
  {
    id: 'S33RJ-b',
    pods: ['L'],
    audio: '/audio/FO-S33-RJ-b.mp3',
    duration: 1.297,
    waveform: '/images/callcatalog/waveforms/S33RJ-b.png',
    colorSpec: '/images/callcatalog/FO-S33-RJ-b.png',
    bwSpec: '/images/callcatalog/S33.png',
  },
  {
    id: 'S33RJ-c',
    pods: ['L'],
    audio: '/audio/FO-S33-RJ-c.mp3',
    duration: 1.874,
    waveform: '/images/callcatalog/waveforms/S33RJ-c.png',
    colorSpec: '/images/callcatalog/FO-S33-RJ-c.png',
    bwSpec: '/images/callcatalog/S33.png',
  },
  {
    id: 'S33RJ-d',
    pods: ['L'],
    audio: '/audio/FO-S33-RJ-d.mp3',
    duration: 1.617,
    waveform: '/images/callcatalog/waveforms/S33RJ-d.png',
    colorSpec: '/images/callcatalog/FO-S33-RJ-d.png',
    bwSpec: '/images/callcatalog/S33.png',
  },
  {
    id: 'S34',
    pods: [],
    audio: '/audio/FO-S34-R.mp3',
    duration: 1.345,
    waveform: '/images/callcatalog/waveforms/S34.png',
    colorSpec: '/images/callcatalog/FO-S34-R.png',
    bwSpec: null,
  },
  {
    id: 'S35R-a',
    pods: [],
    audio: '/audio/FO-S35-R-a.mp3',
    duration: 1.122,
    waveform: '/images/callcatalog/waveforms/S35R-a.png',
    colorSpec: '/images/callcatalog/FO-S35-R-a.png',
    bwSpec: null,
  },
  {
    id: 'S35R-b',
    pods: [],
    audio: '/audio/FO-S35-R-b.mp3',
    duration: 1.372,
    waveform: '/images/callcatalog/waveforms/S35R-b.png',
    colorSpec: '/images/callcatalog/FO-S35-R-b.png',
    bwSpec: null,
  },
  {
    id: 'S36',
    pods: ['L'],
    audio: '/audio/FO-S36.mp3',
    duration: 1.871,
    waveform: '/images/callcatalog/waveforms/S36.png',
    colorSpec: '/images/callcatalog/FO-S36.png',
    bwSpec: '/images/callcatalog/S36.png',
  },
  {
    id: 'S37',
    pods: ['J', 'L'],
    audio: '/audio/FO-S37.mp3',
    duration: 1.403,
    waveform: '/images/callcatalog/waveforms/S37.png',
    colorSpec: '/images/callcatalog/FO-S37.png',
    bwSpec: '/images/callcatalog/S37i.png',
  },
  {
    id: 'S38a',
    pods: [],
    audio: '/audio/FO-S38-a.mp3',
    duration: 1.434,
    waveform: '/images/callcatalog/waveforms/S38a.png',
    colorSpec: '/images/callcatalog/FO-S38-a.png',
    bwSpec: null,
  },
  {
    id: 'S38b',
    pods: [],
    audio: '/audio/FO-S38-b.mp3',
    duration: 1.294,
    waveform: '/images/callcatalog/waveforms/S38b.png',
    colorSpec: '/images/callcatalog/FO-S38-b.png',
    bwSpec: null,
  },
  {
    id: 'S39',
    pods: [],
    audio: '/audio/FO-S39.mp3',
    duration: 1.73,
    waveform: '/images/callcatalog/waveforms/S39.png',
    colorSpec: '/images/callcatalog/FO-S39.png',
    bwSpec: null,
  },
  {
    id: 'S40R-a',
    pods: ['L'],
    audio: '/audio/FO-S40-R-a.mp3',
    duration: 1.902,
    waveform: '/images/callcatalog/waveforms/S40R-a.png',
    colorSpec: '/images/callcatalog/FO-S40-R-a.png',
    bwSpec: '/images/callcatalog/S40.png',
  },
  {
    id: 'S40R-b',
    pods: ['L'],
    audio: '/audio/FO-S40-R-b.mp3',
    duration: 1.185,
    waveform: '/images/callcatalog/waveforms/S40R-b.png',
    colorSpec: '/images/callcatalog/FO-S40-R-b.png',
    bwSpec: '/images/callcatalog/S40.png',
  },
  {
    id: 'S41',
    pods: ['J'],
    audio: null,
    colorSpec: null,
    bwSpec: '/images/callcatalog/S41.png',
  },
  {
    id: 'S42',
    pods: ['J', 'K', 'L'],
    audio: '/audio/FO-S42.mp3',
    duration: 1.822,
    waveform: '/images/callcatalog/waveforms/S42.png',
    colorSpec: '/images/callcatalog/FO-S42.png',
    bwSpec: '/images/callcatalog/S42.png',
  },
  {
    id: 'S44a',
    pods: ['J'],
    audio: '/audio/FO-S44-a.mp3',
    duration: 1.108,
    waveform: '/images/callcatalog/waveforms/S44a.png',
    colorSpec: '/images/callcatalog/FO-S44-a.png',
    bwSpec: '/images/callcatalog/S44.png',
  },
  {
    id: 'S44b',
    pods: ['J'],
    audio: '/audio/FO-S44-b.mp3',
    duration: 0.92,
    waveform: '/images/callcatalog/waveforms/S44b.png',
    colorSpec: '/images/callcatalog/FO-S44-b.png',
    bwSpec: '/images/callcatalog/S44.png',
  },
  {
    id: 'S45',
    pods: [],
    audio: '/audio/FO-S45.mp3',
    duration: 0.998,
    waveform: '/images/callcatalog/waveforms/S45.png',
    colorSpec: '/images/callcatalog/FO-S45.png',
    bwSpec: null,
  },
  {
    id: 'S46',
    pods: [],
    audio: '/audio/FO-S46.mp3',
    duration: 0.814,
    waveform: '/images/callcatalog/waveforms/S46.png',
    colorSpec: '/images/callcatalog/FO-S46.png',
    bwSpec: null,
  },
  {
    id: 'S46b',
    pods: [],
    audio: '/audio/FO-S46-b.mp3',
    duration: 0.87,
    waveform: '/images/callcatalog/waveforms/S46b.png',
    colorSpec: '/images/callcatalog/FO-S46-b.png',
    bwSpec: null,
  },
]
