name: 'Install'
description: 'Install node and dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup node
      id: setup-node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: node-modules
        path: ${{ github.workspace }}/node_modules/
